## Pandas 자료구조

In [1]:
import pandas as pd

### 1. Series

In [51]:
obj = pd.Series([4, 7, -5, 3])
print(obj)
print(type(obj))

0    4
1    7
2   -5
3    3
dtype: int64
<class 'pandas.core.series.Series'>


#### - .values : 값만 출력

In [8]:
obj.values

array([ 4,  7, -5,  3], dtype=int64)

In [11]:
type(obj.values)

numpy.ndarray

#### - .index: 인덱스만 출력

In [10]:
obj.index #range(4)와 유사

RangeIndex(start=0, stop=4, step=1)

In [12]:
type(obj.index)

pandas.core.indexes.range.RangeIndex

#### - 인덱스 지정하기

In [13]:
obj2 = pd.Series([4, 7, -5, 3], index=['d', 'b', 'a', 'c'])
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [14]:
obj2.index

Index(['d', 'b', 'a', 'c'], dtype='object')

#### - 자동 생성한 인덱스와 내가 지정한 인덱스 자료형 다름

In [16]:
type(obj2.index)

pandas.core.indexes.base.Index

#### - numpy에서 인덱스로 값 찾는 것처럼 series에서도 가능

In [17]:
import numpy as np

a = np.array([1, 2, 3, 4])
a[0]

1

In [21]:
print(obj[0], obj[1], obj[2], obj[3])

4 7 -5 3


In [20]:
print(obj2['d'], obj2['b'], obj2['a'], obj2['c'])

4 7 -5 3


#### - 인덱스 사용해서 값 update도 가능

In [22]:
obj2['d'] = 6
obj2

d    6
b    7
a   -5
c    3
dtype: int64

#### - 조건에 따라 값 조회하기

In [23]:
obj2[['c', 'a', 'd']]

c    3
a   -5
d    6
dtype: int64

In [25]:
obj2[obj2 > 0]

d    6
b    7
c    3
dtype: int64

In [26]:
obj2 * 2

d    12
b    14
a   -10
c     6
dtype: int64

#### - np.exp(obj2): e^6, e^7, e^-5, e^3 값 반환

In [28]:
np.exp(obj2)

d     403.428793
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

In [30]:
obj2

d    6
b    7
a   -5
c    3
dtype: int64

In [29]:
'b' in obj2

True

In [31]:
'e' in obj2

False

#### - 딕셔너리를 series로 변환하기

In [32]:
sdata = {'Ohio': 35000, 'Texas':71000, 'Oregon':16000, 'Utah': 5000}
obj3 = pd.Series(sdata)
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [33]:
states = ['California', 'Ohio', 'Oregon', 'Texas']
obj4 = pd.Series(sdata, index=states)
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [34]:
pd.isnull(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [35]:
pd.notnull(obj4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [36]:
obj4.isnull()

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

#### - 인덱스가 둘 다에 존재하지 않으면 NaN, 있으면 계산

In [46]:
print(obj3, obj4)
obj3 + obj4

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64 state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64


California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

#### - 객체.name = "이름" : Series 객체의 이름 지정

In [40]:
obj4.name = "population"
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

#### - 객체.index.name = "이름" : 인덱스 이름 지정

In [41]:
obj4.index.name = 'state'
obj4

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

In [42]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [43]:
obj.index = ['Bob', 'Steve', 'Jeff', 'Ryan']
obj

Bob      4
Steve    7
Jeff    -5
Ryan     3
dtype: int64

### 2. DataFrame

In [47]:
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
        'year': [2000, 2001, 2002, 2001, 2002, 2003],
        'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}
frame = pd.DataFrame(data)
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [48]:
frame.index

RangeIndex(start=0, stop=6, step=1)

In [49]:
frame.columns

Index(['state', 'year', 'pop'], dtype='object')

In [52]:
print(frame.values)
print(type(frame.values))

[['Ohio' 2000 1.5]
 ['Ohio' 2001 1.7]
 ['Ohio' 2002 3.6]
 ['Nevada' 2001 2.4]
 ['Nevada' 2002 2.9]
 ['Nevada' 2003 3.2]]
<class 'numpy.ndarray'>


#### - 객체.head(갯수) : 위에서부터 지정한 갯수만큼 보여줌

In [54]:
frame.head(2)

state  year  pop
0  Ohio  2000  1.5
1  Ohio  2001  1.7

#### - columns에 지정한 순서대로 데이터가 출력됨(없는 컬럼의 경우 NaN으로 채워서 출력)

In [57]:
pd.DataFrame(data, columns=['year', 'state', 'pop'])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [58]:
pd.DataFrame(data, columns=['year', 'state', 'pop', 'debt'])

year   state  pop debt
0  2000    Ohio  1.5  NaN
1  2001    Ohio  1.7  NaN
2  2002    Ohio  3.6  NaN
3  2001  Nevada  2.4  NaN
4  2002  Nevada  2.9  NaN
5  2003  Nevada  3.2  NaN

In [59]:
frame2 = pd.DataFrame(data, columns=['year', 'state', 'pop', 'debt'],
            index = ['one', 'two', 'three', 'four', 'five', 'six'])
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN

In [60]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [61]:
frame2.index

Index(['one', 'two', 'three', 'four', 'five', 'six'], dtype='object')

#### - 열 색인: 객체[컬럼명] | 객체.컬럼명
#### - DataFrame을 색인하니까 Series객체로 반환

In [62]:
frame2['state']

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
six      Nevada
Name: state, dtype: object

In [63]:
type(frame2['state'])

pandas.core.series.Series

In [64]:
frame2.state

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
six      Nevada
Name: state, dtype: object

In [65]:
frame2.year

one      2000
two      2001
three    2002
four     2001
five     2002
six      2003
Name: year, dtype: int64

#### - 행 색인: 객체.loc[로우명]

In [66]:
frame2.loc['one']

year     2000
state    Ohio
pop       1.5
debt      NaN
Name: one, dtype: object

In [68]:
frame2.loc['three']

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

In [69]:
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN

#### - DataFrame에 데이터를 채울 때는 숫자 한개만 넣거나 양쪽 갯수가 맞아야 들어감

In [70]:
frame2['debt'] = 16.5
frame2

year   state  pop  debt
one    2000    Ohio  1.5  16.5
two    2001    Ohio  1.7  16.5
three  2002    Ohio  3.6  16.5
four   2001  Nevada  2.4  16.5
five   2002  Nevada  2.9  16.5
six    2003  Nevada  3.2  16.5

In [73]:
frame2['debt'] = np.arange(6.)
frame2

year   state  pop  debt
one    2000    Ohio  1.5   0.0
two    2001    Ohio  1.7   1.0
three  2002    Ohio  3.6   2.0
four   2001  Nevada  2.4   3.0
five   2002  Nevada  2.9   4.0
six    2003  Nevada  3.2   5.0

#### - 이때는 양쪽의 갯수가 안맞긴 하지만 인덱스가 지정되어 있으므로 해당 인덱스 값이 채워짐

In [75]:
val = pd.Series([-1.2, -1.5, -1.7], index=['two', 'four', 'five'])
val

two    -1.2
four   -1.5
five   -1.7
dtype: float64

In [77]:
frame2['debt'] = val
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN

In [79]:
frame2.state == 'Ohio'

one       True
two       True
three     True
four     False
five     False
six      False
Name: state, dtype: bool

In [80]:
frame2['eastern'] = frame2.state == 'Ohio'
frame2

year   state  pop  debt  eastern
one    2000    Ohio  1.5   NaN     True
two    2001    Ohio  1.7  -1.2     True
three  2002    Ohio  3.6   NaN     True
four   2001  Nevada  2.4  -1.5    False
five   2002  Nevada  2.9  -1.7    False
six    2003  Nevada  3.2   NaN    False

#### - del 객체[컬럼명] : 해당 컬럼 삭제

In [81]:
del frame2['eastern']
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

#### - 딕셔너리안에 또 딕셔너리가 있는 형태이면 처음 키값이 컬럼, 그 안의 키값이 로우로 변환함

In [82]:
pop = {'Nevada': {2001: 2.4, 2002: 2.9},
       'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}
frame3 = pd.DataFrame(pop)
frame3

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2000     NaN   1.5

In [83]:
frame3.T

2001  2002  2000
Nevada   2.4   2.9   NaN
Ohio     1.7   3.6   1.5

In [84]:
pd.DataFrame(pop, index=[2001, 2002, 2003])

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2003     NaN   NaN

In [85]:
frame3['Ohio'][:-1]
frame3['Nevada'][:2]

2001    1.7
2002    3.6
Name: Ohio, dtype: float64

In [88]:
pdata = {'Ohio': frame3['Ohio'][:-1],
        'Nevada':frame3['Nevada'][:2]}

pd.DataFrame(pdata)

Ohio  Nevada
2001   1.7     2.4
2002   3.6     2.9

#### - DataFrame명은 지정해도 나오지는 않음
#### - 로우, 컬럼명은 나옴

In [89]:
frame3.name = "population"
frame3

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2000     NaN   1.5

In [90]:
frame3.index.name = 'year'
frame3.columns.name = 'state'
frame3

state  Nevada  Ohio
year               
2001      2.4   1.7
2002      2.9   3.6
2000      NaN   1.5

In [91]:
frame3.values

array([[2.4, 1.7],
       [2.9, 3.6],
       [nan, 1.5]])

In [92]:
type(frame3.values)

numpy.ndarray

In [93]:
frame2.values

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, -1.2],
       [2002, 'Ohio', 3.6, nan],
       [2001, 'Nevada', 2.4, -1.5],
       [2002, 'Nevada', 2.9, -1.7],
       [2003, 'Nevada', 3.2, nan]], dtype=object)

In [94]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

### 3. Index

In [100]:
obj = pd.Series(range(3), index=['a', 'b', 'c'])
index = obj.index
index

Index(['a', 'b', 'c'], dtype='object')

In [101]:
index[1:]

Index(['b', 'c'], dtype='object')

In [102]:
labels = pd.Index(np.arange(3))
labels

Int64Index([0, 1, 2], dtype='int64')

In [104]:
obj2 = pd.Series([1.5, -2.5, 0], index=labels)
obj2

0    1.5
1   -2.5
2    0.0
dtype: float64

In [105]:
obj2.index is labels

True

In [106]:
frame3

state  Nevada  Ohio
year               
2001      2.4   1.7
2002      2.9   3.6
2000      NaN   1.5

In [107]:
frame3.columns

Index(['Nevada', 'Ohio'], dtype='object', name='state')

In [108]:
'Ohio' in frame3.columns

True

In [109]:
2003 in frame3.index

False

In [110]:
dup_labels = pd.Index(['foo', 'foo', 'bar', 'bar'])
dup_labels

Index(['foo', 'foo', 'bar', 'bar'], dtype='object')

### 실습

#### - 딕셔너리 -> 시리즈 변환(index, values 출력)

In [145]:
dict_data = {'a':1, 'b':2, 'c':3}

x = pd.Series(dict_data)
print(x, x.index, x.values, sep='\n')

a    1
b    2
c    3
dtype: int64
Index(['a', 'b', 'c'], dtype='object')
[1 2 3]


#### - 리스트 -> 시리즈 변환(index, values 출력)

In [146]:
list_data = ['2019-01-02', 3.14, 'ABC', 100, True]

x = pd.Series(list_data)
print(x, x.index, x.values, sep='\n')

0    2019-01-02
1          3.14
2           ABC
3           100
4          True
dtype: object
RangeIndex(start=0, stop=5, step=1)
['2019-01-02' 3.14 'ABC' 100 True]


#### - 튜플 -> 시리즈 변환(index, values 출력)

In [147]:
tup_data = ('영인', '2020-05-01', '여', True)

x = pd.Series(tup_data)
print(x, x.index, x.values, sep='\n')

0            영인
1    2020-05-01
2             여
3          True
dtype: object
RangeIndex(start=0, stop=4, step=1)
['영인' '2020-05-01' '여' True]


#### - 튜플 -> 시리즈 변환(index 설정)

In [148]:
tup_data = ('영인', '2020-05-01', '여', True)
index_name = ['이름', '생년월일', '성별', '학생여부']

x = pd.Series(tup_data, index=index_name)
print(x, x.index, x.values, sep='\n')

이름              영인
생년월일    2020-05-01
성별               여
학생여부          True
dtype: object
Index(['이름', '생년월일', '성별', '학생여부'], dtype='object')
['영인' '2020-05-01' '여' True]


#### - 시리즈 원소 선택

In [149]:
tup_data = ('영인', '2020-05-01', '여', True)
index_name = ['이름', '생년월일', '성별', '학생여부']

x = pd.Series(tup_data, index=index_name)
x

이름              영인
생년월일    2020-05-01
성별               여
학생여부          True
dtype: object

In [152]:
# '영인' 값 선택하기(index, 이름)
print(x[0], x['이름'])

영인 영인


#### - 인덱스로 슬라이싱할 때는 두번째 값이 포함되지 않음, 이름으로 슬라이싱할 때는 둘다 포함

In [157]:
# '2020-05-01'과 '여' 값 선택하기(index, 이름, index 슬라이싱, 이름 슬라이싱)
print(x[[1, 2]], x[['생년월일', '성별']], sep='\n')
print(x[1:3], x['생년월일':'성별'], sep='\n')

생년월일    2020-05-01
성별               여
dtype: object
생년월일    2020-05-01
성별               여
dtype: object
생년월일    2020-05-01
성별               여
dtype: object
생년월일    2020-05-01
성별               여
dtype: object


#### - 딕셔너리 -> 데이터프레임 변환

In [144]:
dict_data = {'c0':[1, 2, 3], 'c1':[4, 5, 6], 'c3':'[10, 11, 12]', 'c4':[13, 14, 15]}

x = pd.DataFrame(dict_data)
x

c0  c1            c3  c4
0   1   4  [10, 11, 12]  13
1   2   5  [10, 11, 12]  14
2   3   6  [10, 11, 12]  15

#### - 행 인덱스/열 이름 설정

In [161]:
df = pd.DataFrame([[15, '남', '덕영중'], [17, '여', '수리중']],
                 index=['준서', '예은'],
                 columns=['나이', '성별', '학교'])
df

나이 성별   학교
준서  15  남  덕영중
예은  17  여  수리중

In [162]:
# 준서, 예은 -> 학생1, 학생2로 변경

df.index = ['학생1', '학생2']
df

나이 성별   학교
학생1  15  남  덕영중
학생2  17  여  수리중

In [163]:
# 나이, 성별, 학교 -> 연령, 남녀, 소속으로 변경

df.columns = ['연령', '남녀', '소속']
df

연령 남녀   소속
학생1  15  남  덕영중
학생2  17  여  수리중

#### - 위의 방법은 양쪽의 데이터 개수가 맞아야 바꿔짐
#### - 객체.rename(): 일부만 변경하고 싶을 때 사용, 원본을 바꾸지 않고 새로운 객체 생성함(원본에 반영하고 싶으면 inplace=True 옵션을 추가)

In [164]:
df = pd.DataFrame([[15, '남', '덕영중'], [17, '여', '수리중']],
                 index=['준서', '예은'],
                 columns=['나이', '성별', '학교'])

In [165]:
df.rename(columns={'나이':'연령', '성별':'남녀', '학교':'소속'})
df.rename(index={'준서':'학생1', '예은':'학생2'})

나이 성별   학교
학생1  15  남  덕영중
학생2  17  여  수리중

In [166]:
df

나이 성별   학교
준서  15  남  덕영중
예은  17  여  수리중

In [167]:
df.rename(columns={'나이':'연령', '성별':'남녀', '학교':'소속'}, inplace=True)
df.rename(index={'준서':'학생1', '예은':'학생2'}, inplace=True)
df

연령 남녀   소속
학생1  15  남  덕영중
학생2  17  여  수리중

## 중요한 기능들

### 1. 재색인

In [169]:
obj = pd.Series([4, 7, -5, 3], ['d', 'b', 'a', 'c'])
obj

d    4
b    7
a   -5
c    3
dtype: int64

In [171]:
obj2 = obj.reindex(['a', 'b', 'c', 'd', 'e'])
obj2

a   -5.0
b    7.0
c    3.0
d    4.0
e    NaN
dtype: float64

In [172]:
obj3 = pd.Series(['blue', 'purple', 'yellow'])
obj3

0      blue
1    purple
2    yellow
dtype: object

#### - 객체.reindex(값, method='ffill') : 없는 인덱스는 추가하고 해당값은 전값과 똑같이 채우기

In [175]:
obj3.reindex(range(6), method='ffill')

0      blue
1    purple
2    yellow
3    yellow
4    yellow
5    yellow
dtype: object

In [176]:
np.arange(9).reshape(3, 3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [178]:
frame = pd.DataFrame(np.arange(9).reshape(3, 3),
                    index=['a', 'b', 'c'],
                    columns=['Ohio', 'Texas', 'California'])

frame

Ohio  Texas  California
a     0      1           2
b     3      4           5
c     6      7           8

In [179]:
frame2 = frame.reindex(['a', 'b', 'c', 'd'])
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   3.0    4.0         5.0
c   6.0    7.0         8.0
d   NaN    NaN         NaN

In [180]:
states = ['Texas', 'Utah', 'California']
frame.reindex(columns=states)

Texas  Utah  California
a      1   NaN           2
b      4   NaN           5
c      7   NaN           8

### 2. 로우나 컬럼 삭제하기

In [188]:
obj = pd.Series(np.arange(5), index=['a', 'b', 'c', 'd', 'e'])
obj

a    0
b    1
c    2
d    3
e    4
dtype: int32

#### - 객체.drop(인덱스명) : 해당 인덱스 값 삭제, inplace=True해줘야 원본도 바뀜

In [189]:
obj.drop('c')

a    0
b    1
d    3
e    4
dtype: int32

In [191]:
obj.drop(['d', 'c'])

a    0
b    1
e    4
dtype: int32

In [195]:
data = pd.DataFrame(np.arange(16).reshape(4, 4),
            index=['Ohio', 'Colorado', 'Utah', 'New York'],
            columns=['one', 'two', 'three', 'four'])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [198]:
data.drop('Colorado')

one  two  three  four
Ohio        0    1      2     3
Utah        8    9     10    11
New York   12   13     14    15

#### - 로우를 삭제할 때는 axis=0 | axis='index' 

In [200]:
data.drop(['Colorado', 'Ohio'])

one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [205]:
data.drop(['Colorado', 'Ohio'], axis=0)

one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [207]:
data.drop(['Colorado', 'Ohio'], axis='index')

one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

#### - 컬럼을 삭제할 때는 axis=1 | axis='columns'

In [202]:
data.drop('two', axis=1)

one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [204]:
data.drop(['two', 'four'], axis=1)

one  three
Ohio        0      2
Colorado    4      6
Utah        8     10
New York   12     14

In [208]:
obj

a    0
b    1
c    2
d    3
e    4
dtype: int32

In [210]:
obj.drop('c', inplace=True)
obj

a    0
b    1
d    3
e    4
dtype: int32

#### <정리>

#### - 일반적인 연산(df.min, df.max, df.mean ...)에 대해서는 축을 따라서 연산
#### - 삭제하는 경우에는 그 축을 삭제

### 3. 색인하기, 선택하기, 거르기

In [219]:
obj = pd.Series(np.arange(4.), index=['a', 'b', 'c', 'd'])
obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [220]:
obj['b']

1.0

In [221]:
obj[1]

1.0

In [222]:
obj[2:4]

c    2.0
d    3.0
dtype: float64

In [223]:
obj[['b', 'a', 'd']]

b    1.0
a    0.0
d    3.0
dtype: float64

In [224]:
obj[[1, 3]]

b    1.0
d    3.0
dtype: float64

In [225]:
obj[obj < 2]

a    0.0
b    1.0
dtype: float64

In [226]:
obj['b':'c']

b    1.0
c    2.0
dtype: float64

In [227]:
obj['b':'c'] = 5
obj

a    0.0
b    5.0
c    5.0
d    3.0
dtype: float64

In [228]:
data = pd.DataFrame(np.arange(16).reshape(4, 4),
            index = ['Ohio', 'Colorado', 'Utah', 'New York'],
            columns = ['one', 'two', 'three', 'four'])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [229]:
data['two']

Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int32

In [230]:
data[['three', 'one']]

three  one
Ohio          2    0
Colorado      6    4
Utah         10    8
New York     14   12

In [236]:
data[data['three'] > 5]

one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

#### - 조건에 해당하는 숫자만 출력하고 나머지는 NaN으로 출력

In [238]:
data[data < 5]

one  two  three  four
Ohio      0.0  1.0    2.0   3.0
Colorado  4.0  NaN    NaN   NaN
Utah      NaN  NaN    NaN   NaN
New York  NaN  NaN    NaN   NaN

#### - loc, iloc 선택하기
#### - loc : 이름으로 색인
#### - iloc: 숫자로 색인

In [242]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [264]:
print(data.loc['Colorado'])  # Series
data.loc[['Colorado']]       # DataFrame

one      4
two      5
three    6
four     7
Name: Colorado, dtype: int32


one  two  three  four
Colorado    4    5      6     7

In [265]:
print(data.loc['Colorado', ['two', 'three']])  # Series
data.loc[['Colorado'], ['two', 'three']]       # DataFrame

two      5
three    6
Name: Colorado, dtype: int32


two  three
Colorado    5      6

In [266]:
print(data.iloc[1, [1, 2]])  # Series
data.iloc[[1], [1, 2]]       # DataFrame

two      5
three    6
Name: Colorado, dtype: int32


two  three
Colorado    5      6

In [267]:
print(data.iloc[2, [3, 0, 1]]) # Series
data.iloc[[2], [3, 0, 1]]      # DataFrame

four    11
one      8
two      9
Name: Utah, dtype: int32


four  one  two
Utah    11    8    9

In [268]:
print(data.iloc[2])  # Series
data.iloc[[2]]       # DataFrame

one       8
two       9
three    10
four     11
Name: Utah, dtype: int32


one  two  three  four
Utah    8    9     10    11

In [282]:
data.iloc[[1, 2], [3, 0, 1]]

four  one  two
Colorado     7    4    5
Utah        11    8    9

In [281]:
data.iloc[:3, 1:]

two  three  four
Ohio        1      2     3
Colorado    5      6     7
Utah        9     10    11

In [275]:
print(data.loc['Utah'])  # Series
data.loc[['Utah']]       # DataFrame 

one       8
two       9
three    10
four     11
Name: Utah, dtype: int32


pandas.core.series.Series

In [285]:
data.loc[:'Utah', 'two']

Ohio        1
Colorado    5
Utah        9
Name: two, dtype: int32

#### - 불리언 색인할 때나 슬라이싱으로 가져올때는 loc, iloc 쓰지 않아도 행 가져옴

In [288]:
data[:2]

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7

In [289]:
data[data > 5]

one   two  three  four
Ohio       NaN   NaN    NaN   NaN
Colorado   NaN   NaN    6.0   7.0
Utah       8.0   9.0   10.0  11.0
New York  12.0  13.0   14.0  15.0

In [262]:
data.iloc[:, :3]

one  two  three
Ohio        0    1      2
Colorado    4    5      6
Utah        8    9     10
New York   12   13     14

In [261]:
data.iloc[:, :3][data['three'] > 5]

one  two  three
Colorado    4    5      6
Utah        8    9     10
New York   12   13     14

### 4. 정수 색인

In [290]:
ser = pd.Series(np.arange(3,))
ser

0    0
1    1
2    2
dtype: int32

In [291]:
ser[:1]

0    0
dtype: int32

#### - loc: 라벨 색인
#### - iloc: 정수 색인, 이때는 마지막 값 포함 안됨

In [292]:
ser.loc[:1]

0    0
1    1
dtype: int32

In [293]:
ser.iloc[:1]

0    0
dtype: int32

### 실습

#### - 행 삭제

In [294]:
exam_data = {'수학' : [ 90, 80, 70], '영어' : [ 98, 89, 95],
             '음악' : [ 85, 95, 100], '체육' : [ 100, 90, 90]}

df = pd.DataFrame(exam_data, index=['서준', '우현', '인아'])
df

수학  영어   음악   체육
서준  90  98   85  100
우현  80  89   95   90
인아  70  95  100   90

In [295]:
# 서준 행 삭제

df.drop('서준')

수학  영어   음악  체육
우현  80  89   95  90
인아  70  95  100  90

In [296]:
# 서준, 우현 행 삭제

df.drop(['서준', '우현'])

수학  영어   음악  체육
인아  70  95  100  90

#### - 열 삭제

In [297]:
# 수학 열 삭제

df.drop('수학', axis=1)

영어   음악   체육
서준  98   85  100
우현  89   95   90
인아  95  100   90

In [298]:
# 수학, 영어 열 삭제

df.drop(['수학', '영어'], axis=1)

음악   체육
서준   85  100
우현   95   90
인아  100   90

#### - 행 선택

In [301]:
# 서준 행 선택(label, 정수 색인)

df.loc['서준']

수학     90
영어     98
음악     85
체육    100
Name: 서준, dtype: int64

In [302]:
df.iloc[0]

수학     90
영어     98
음악     85
체육    100
Name: 서준, dtype: int64

In [303]:
# 서준, 우현 행 선택(라벨 색인, 정수 색인, 슬라이싱)

df.loc[['서준', '우현']]

수학  영어  음악   체육
서준  90  98  85  100
우현  80  89  95   90

In [329]:
df.loc['서준':'우현']

수학  영어  음악   체육
서준  90  98  85  100
우현  80  89  95   90

In [310]:
df.iloc[[0, 1]]

수학  영어  음악   체육
서준  90  98  85  100
우현  80  89  95   90

In [313]:
df[:2]

수학  영어  음악   체육
서준  90  98  85  100
우현  80  89  95   90

#### - 열 선택

In [315]:
# 수학 열 선택

df['수학']

서준    90
우현    80
인아    70
Name: 수학, dtype: int64

In [330]:
df.수학

서준    90
우현    80
인아    70
Name: 수학, dtype: int64

In [317]:
# 음악, 체육 열 선택

df[['음악', '체육']]

음악   체육
서준   85  100
우현   95   90
인아  100   90

#### - 원소 선택

In [323]:
df

수학  영어   음악   체육
서준  90  98   85  100
우현  80  89   95   90
인아  70  95  100   90

In [322]:
# 서준의 음악 점수

df.loc['서준', '음악']

85

In [332]:
df.iloc[0, 2]

85

In [324]:
# 서준의 음악, 체육 점수

df.loc['서준', ['음악','체육']]

음악     85
체육    100
Name: 서준, dtype: int64

In [333]:
df.iloc[0, [2, 3]]

음악     85
체육    100
Name: 서준, dtype: int64

In [327]:
# 서준, 우현의 음악, 체육 점수

df.loc[['서준', '우현'], ['음악', '체육']]

음악   체육
서준  85  100
우현  95   90

In [334]:
df.iloc[[0, 1], [2, 3]]

음악   체육
서준  85  100
우현  95   90

#### - 열 추가

In [335]:
df

수학  영어   음악   체육
서준  90  98   85  100
우현  80  89   95   90
인아  70  95  100   90

In [337]:
# 국어 열 추가, 값은 80점 지정

df['국어'] = 80
df

수학  영어   음악   체육  국어
서준  90  98   85  100  80
우현  80  89   95   90  80
인아  70  95  100   90  80

#### - 행 추가

In [340]:
# 본인 이름으로 행 추가

df.loc['재효'] = [90, 95, 80, 70, 75]
df

수학  영어   음악   체육  국어
서준  90  98   85  100  80
우현  80  89   95   90  80
인아  70  95  100   90  80
재효  90  95   80   70  75

In [341]:
# 서준의 체육 점수를 80점으로 변경

df.loc['서준', '체육'] = 80
df

수학  영어   음악  체육  국어
서준  90  98   85  80  80
우현  80  89   95  90  80
인아  70  95  100  90  80
재효  90  95   80  70  75

In [342]:
# 서준의 음악, 체육 점수 변경

df.loc['서준', ['음악', '체육']] = [90, 95]
df

수학  영어   음악  체육  국어
서준  90  98   90  95  80
우현  80  89   95  90  80
인아  70  95  100  90  80
재효  90  95   80  70  75

In [343]:
# 과목이 행, 학생이 열

df.T

서준  우현   인아  재효
수학  90  80   70  90
영어  98  89   95  95
음악  90  95  100  80
체육  95  90   90  70
국어  80  80   80  75

#### - 특정 열을 행 인덱스로 설정

In [410]:
exam_data = {'이름' : [ '서준', '우현', '인아'],
             '수학' : [ 90, 80, 70],
             '영어' : [ 98, 89, 95],
             '음악' : [ 85, 95, 100],
             '체육' : [ 100, 90, 90]}
df = pd.DataFrame(exam_data)
df

이름  수학  영어   음악   체육
0  서준  90  98   85  100
1  우현  80  89   95   90
2  인아  70  95  100   90

In [411]:
# 이름 열을 행 인덱스로 지정

df.set_index(['이름'], inplace = True)
df

수학  영어   음악   체육
이름                  
서준  90  98   85  100
우현  80  89   95   90
인아  70  95  100   90

In [412]:
df.reindex(['인아', '서준', '경희'])

수학    영어     음악     체육
이름                          
인아  70.0  95.0  100.0   90.0
서준  90.0  98.0   85.0  100.0
경희   NaN   NaN    NaN    NaN

In [414]:
df.reset_index()

이름  수학  영어   음악   체육
0  서준  90  98   85  100
1  우현  80  89   95   90
2  인아  70  95  100   90

### 5. 산술 연산과 데이터 정렬

In [346]:
s1 = pd.Series([7.3, -2.5, 3.4, 1.5], index=['a', 'c', 'd', 'e'])
s2 = pd.Series([-2.1, 3.6, -1.5, 4, 3.1], index=['a', 'c', 'e', 'f', 'g'])

In [347]:
s1

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64

In [348]:
s2

a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

#### - 한쪽에만 있는 데이터는 NaN으로 채워짐

In [349]:
s1 + s2

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [350]:
df1 = pd.DataFrame({'A': [1, 2]})
df2 = pd.DataFrame({'B': [3, 4]})

In [351]:
df1

A
0  1
1  2

In [352]:
df2

B
0  3
1  4

In [353]:
df1 + df2

A   B
0 NaN NaN
1 NaN NaN

In [379]:
df1 = pd.DataFrame(np.arange(12).reshape(3, 4), columns=list('abcd'))
df2 = pd.DataFrame(np.arange(20).reshape(4, 5), columns=list('abcde'))
df2.loc[1, 'b'] = np.nan

In [380]:
df1

a  b   c   d
0  0  1   2   3
1  4  5   6   7
2  8  9  10  11

In [381]:
df2

a     b   c   d   e
0   0   1.0   2   3   4
1   5   NaN   7   8   9
2  10  11.0  12  13  14
3  15  16.0  17  18  19

In [382]:
df1 + df2

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0   NaN  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

#### - NaN인 부분은 0으로 채워서 연산, 둘 중 하나라도 값 있으면 그 값 채워서 나옴

In [383]:
df1.add(df2, fill_value=0)

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0   5.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

#### - 1/df1 | df1.rdiv(1) : 브로드캐스팅되어서 가능

In [360]:
1 / df1

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [384]:
df1.rdiv(1)

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [361]:
df1.reindex(columns=df2.columns)

a  b   c   d   e
0  0  1   2   3 NaN
1  4  5   6   7 NaN
2  8  9  10  11 NaN

In [362]:
df1.reindex(columns=df2.columns, fill_value=0)

a  b   c   d  e
0  0  1   2   3  0
1  4  5   6   7  0
2  8  9  10  11  0

#### - (참고) 넘파이 산술연산 예

In [363]:
arr = np.arange(12.).reshape(3, 4)
arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [364]:
arr[0]

array([0., 1., 2., 3.])

In [365]:
arr * 2

array([[ 0.,  2.,  4.,  6.],
       [ 8., 10., 12., 14.],
       [16., 18., 20., 22.]])

#### - 열의 크기가 맞으면 arr-arr[0]과 같은 연산 가능

In [366]:
arr - arr[0]

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

In [372]:
frame = pd.DataFrame(np.arange(12.).reshape(4, 3),
            columns=list('bde'),
            index=['Utah', 'Ohio', 'Texas', 'Oregon'])

series = frame.iloc[0]

In [373]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [374]:
series

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

In [375]:
frame-series

b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

In [376]:
series2 = pd.Series(range(3), index=['b','e','f'])
series2

b    0
e    1
f    2
dtype: int64

In [377]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [378]:
frame + series2

b   d     e   f
Utah    0.0 NaN   3.0 NaN
Ohio    3.0 NaN   6.0 NaN
Texas   6.0 NaN   9.0 NaN
Oregon  9.0 NaN  12.0 NaN

In [385]:
series3 = frame['d']
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [394]:
series3

Utah       1.0
Ohio       4.0
Texas      7.0
Oregon    10.0
Name: d, dtype: float64

In [388]:
frame - series3

Ohio  Oregon  Texas  Utah   b   d   e
Utah     NaN     NaN    NaN   NaN NaN NaN NaN
Ohio     NaN     NaN    NaN   NaN NaN NaN NaN
Texas    NaN     NaN    NaN   NaN NaN NaN NaN
Oregon   NaN     NaN    NaN   NaN NaN NaN NaN

In [397]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [398]:
series3

Utah       1.0
Ohio       4.0
Texas      7.0
Oregon    10.0
Name: d, dtype: float64

In [390]:
frame.sub(series3, axis=0)

b    d    e
Utah   -1.0  0.0  1.0
Ohio   -1.0  0.0  1.0
Texas  -1.0  0.0  1.0
Oregon -1.0  0.0  1.0

### 실습

In [399]:
student1 = pd.Series({'국어':100, '영어':80, '수학':90})
student1

국어    100
영어     80
수학     90
dtype: int64

In [400]:
# 과목별 점수를 100으로 나눠보기

student1/100

국어    1.0
영어    0.8
수학    0.9
dtype: float64

In [401]:
student1.div(100)

국어    1.0
영어    0.8
수학    0.9
dtype: float64

In [402]:
student1 = pd.Series({'국어':100, '영어':80, '수학':90})
student2 = pd.Series({'수학':80, '국어':90, '영어':80})

In [403]:
# 두 학생의 평균

(student1 + student2)/2

국어    95.0
수학    85.0
영어    80.0
dtype: float64

In [404]:
student1.add(student2).div(2)

국어    95.0
수학    85.0
영어    80.0
dtype: float64

In [405]:
student1 = pd.Series({'국어':np.nan, '영어':80, '수학':90})
student2 = pd.Series({'수학':80, '국어':90})

In [406]:
student1.add(student2, fill_value=0).div(2)

국어    45.0
수학    85.0
영어    40.0
dtype: float64